# Generated by Django 4.1.3 on 2023-01-17 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="colour",
            fields=[
                ("color", models.AutoField(primary_key=True, serialize=False)),
                (
                    "color_name",
                    models.CharField(max_length=100, verbose_name="Colour Name"),
                ),
            ],
            options={
                "verbose_name": "Colour",
            },
        ),
        migrations.CreateModel(
            name="Wing_Image",
            fields=[
                ("wing", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="static\\db_wingimages", verbose_name="Image"
                    ),
                ),
                (
                    "hash",
                    models.CharField(max_length=33, verbose_name="MD5 Hash of Image"),
                ),
                (
                    "dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wing Image",
            },
        ),
        migrations.CreateModel(
            name="w_shape",
            fields=[
                ("wshape", models.AutoField(primary_key=True, serialize=False)),
                ("ws_pred", models.CharField(max_length=10, verbose_name="Prediction")),
                (
                    "ws_normal_prob",
                    models.FloatField(
                        max_length=100, verbose_name="Probability % of Normal"
                    ),
                ),
                (
                    "ws_mutated_prob",
                    models.FloatField(
                        max_length=100, verbose_name="Probability % of Mutant"
                    ),
                ),
                (
                    "ws_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wing Shape",
            },
        ),
        migrations.CreateModel(
            name="w_dimen",
            fields=[
                ("wdimen", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wd_area",
                    models.FloatField(max_length=100, verbose_name="Wing overall Area"),
                ),
                (
                    "wd_peri",
                    models.FloatField(
                        max_length=100, verbose_name="Wing overall Perimeter"
                    ),
                ),
                (
                    "wd_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wing Dimension",
            },
        ),
        migrations.CreateModel(
            name="w_bristles",
            fields=[
                ("wbrisltes", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bristle_count",
                    models.IntegerField(verbose_name="Wing overall Bristles"),
                ),
                (
                    "wb_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wing Bristles",
            },
        ),
        migrations.CreateModel(
            name="Eye_Image",
            fields=[
                ("eye", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="static\\db_eyeimages", verbose_name="Image"
                    ),
                ),
                (
                    "hash",
                    models.CharField(max_length=33, verbose_name="MD5 Hash of Image"),
                ),
                (
                    "dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eye Image",
            },
        ),
        migrations.CreateModel(
            name="e_ommatidium",
            fields=[
                ("emodel", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ommatidium_count",
                    models.IntegerField(verbose_name="Eye overall Ommatidium"),
                ),
                (
                    "eo_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eye Ommatidium",
            },
        ),
        migrations.CreateModel(
            name="e_dimension",
            fields=[
                ("edimension", models.AutoField(primary_key=True, serialize=False)),
                (
                    "earea",
                    models.FloatField(max_length=100, verbose_name="Eye overall Area"),
                ),
                (
                    "eperimeter",
                    models.FloatField(
                        max_length=100, verbose_name="Eye overall Perimeter"
                    ),
                ),
                (
                    "ed_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eye Dimension",
            },
        ),
        migrations.CreateModel(
            name="e_colour",
            fields=[
                ("ecolour", models.AutoField(primary_key=True, serialize=False)),
                (
                    "colour_1",
                    models.FloatField(max_length=100, verbose_name="Colour 1 %"),
                ),
                (
                    "colour_2",
                    models.FloatField(max_length=100, verbose_name="Colour 2 %"),
                ),
                (
                    "colour_3",
                    models.FloatField(max_length=100, verbose_name="Colour 3 %"),
                ),
                (
                    "colour_4",
                    models.FloatField(max_length=100, verbose_name="Colour 4 %"),
                ),
                (
                    "pred",
                    models.CharField(max_length=10, verbose_name="Predicted Colour"),
                ),
                (
                    "col1",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="a",
                        to="Droso.colour",
                        verbose_name="Colour 1 ID",
                    ),
                ),
                (
                    "col2",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b",
                        to="Droso.colour",
                        verbose_name="Colour 2 ID",
                    ),
                ),
                (
                    "col3",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="c",
                        to="Droso.colour",
                        verbose_name="Colour 3 ID",
                    ),
                ),
                (
                    "col4",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="d",
                        to="Droso.colour",
                        verbose_name="Colour 4 ID",
                    ),
                ),
                (
                    "ec_o_img",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eye Colour",
            },
        ),
    ]
