# Generated by Django 4.1.3 on 2022-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="e_colour",
            fields=[
                ("ecolour", models.AutoField(primary_key=True, serialize=False)),
                ("colour1", models.FloatField(max_length=100)),
                ("colour2", models.FloatField(max_length=100)),
                ("colour3", models.FloatField(max_length=100)),
                ("pred", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="e_ommatidium",
            fields=[
                ("emodel", models.AutoField(primary_key=True, serialize=False)),
                ("ommatidium_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="e_shape",
            fields=[
                ("eshape", models.AutoField(primary_key=True, serialize=False)),
                ("earea", models.FloatField(max_length=100)),
                ("eperimeter", models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="w_bristles",
            fields=[
                ("wbrisltes", models.AutoField(primary_key=True, serialize=False)),
                ("bristle_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="w_dimen",
            fields=[
                ("wdimen", models.AutoField(primary_key=True, serialize=False)),
                ("wd_area", models.FloatField(max_length=100)),
                ("wd_peri", models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="w_shape",
            fields=[
                ("wshape", models.AutoField(primary_key=True, serialize=False)),
                ("ws_pred", models.CharField(max_length=10)),
                ("ws_normal_prob", models.FloatField(max_length=100)),
                ("ws_mutated_prob", models.FloatField(max_length=100)),
            ],
        ),
    ]
