# Generated by Django 4.1.2 on 2022-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="w_dimen",
            fields=[
                ("wdimen", models.AutoField(primary_key=True, serialize=False)),
                ("wd_o_img", models.CharField(max_length=600)),
                ("wd_b_img", models.CharField(max_length=600)),
                ("wd_area", models.FloatField(max_length=100)),
                ("wd_peri", models.FloatField(max_length=100)),
                ("wd_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="w_shape",
            fields=[
                ("wshape", models.AutoField(primary_key=True, serialize=False)),
                ("ws_o_img", models.CharField(max_length=600)),
                ("ws_pred", models.CharField(max_length=10)),
                ("ws_normal_prob", models.FloatField(max_length=100)),
                ("ws_mutated_prob", models.FloatField(max_length=100)),
                ("ws_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
