# Generated by Django 4.1.3 on 2022-12-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Droso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eye_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/db_eyeimages")),
            ],
        ),
        migrations.CreateModel(
            name="Wing_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/db_wingimages")),
            ],
        ),
        migrations.AddField(
            model_name="w_dimen",
            name="wd_o_img",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Droso.wing_image",
            ),
            preserve_default=False,
        ),
    ]
