# Generated by Django 4.1.3 on 2022-12-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Droso", "0002_eye_image_wing_image_w_dimen_wd_o_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="w_dimen",
            name="wd_o_img",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Droso.wing_image",
            ),
        ),
    ]
